### PR TITLE
Fixes #1367 - streamEST - FlowAnywhere

### LINKED ISSUE #1367: streamEST - FlowAnywhere
Aiming to complete FY22.

Goal: move streamEST FlowAnywhere into StreamStats. 

**Steps**

- [x] Create "Configure Flow Anywhere Method" button
- [x] Create "Flow Anywhere Method" modal
- [x] Add "FLA" application to Iowa in the appConfig.js
- [x] Add Flow Anywhere services to the appConfig.js
- [x] Add space between the extension buttons (FDCTM and FLA)

In the modal:
- [x] Compute & display the basin drainage area 
- [x] Show list of gages from the https://gis.wim.usgs.gov/arcgis/rest/services/IowaStreamEst/FlowAnywhere/MapServer/1/query service in the modal
- ~[ ] Add additional attributes to those gages:~ Omitting for now because this was not in StreamEst
      - ~Include link to the gage page
      - Station Type
      - Is Regulated?
      - Distance from Click Point (mi)
      - Start Date
      - End Date~
- [x] Include a "Select Gage" button and make functional
- [x] Enabled styling on the gage table
- [x] Enable the date selector
- [x] Verify that all the inputs are complete and valid
- [x] Make the modal look nice
- [x] Add blurb to explain Flow Anywhere Model and the purpose of the modal and where the results will show up
- [ ] Add loader to reference gage table
- [x] Make sure selections are saved when modal is re-opened

In the final report:
- [x] Add new section to report
- [x] Compute results via https://streamstats.usgs.gov/regressionservices/models/FLA/estimate?state=IA
- [x] Include input data 
- [x] Include tabular data
- [x] Include graphical results
- [x] Make sure results are included in the downloaded CSV
- [x] Make sure results are included in the printed PDF
- [x] Include citation
- [x] Add warnings from results

At the end:
- [x] Ensure all functionality from StreamEst has been replicated
- [x] Compare results with StreamEst results
- [x] Ensure both FDCTM and FLA can be completed at the same time
- [x] Handle service errors

**Resources**
- StreamEst client: https://wim.usgs.gov/streamest/
- Report: https://pubs.usgs.gov/sir/2012/5232/

### PR DESCRIPTION
**Pull request by amedenblik**
Closes #1367 

~Sometimes the Flow Anywhere Method results are not quite ready when the report is opened, but I was struggling to figure out how to force the report to wait to open until the results were ready, in combination with other calculations of regression region equations, extensions, etc.~ fixed with latest commit

### CODE REVIEW

**Comment by HansVraga** [comment]
Do we put a placeholder `still calculating` message or loading spinner in the flow anywhere section of the report and replace it when the results are calculated?

**Comment by amedenblik** [comment]
Good idea, @HansVraga 👍

**Comment by amedenblik** [comment]
Fixed report loading issue

**Comment by amedenblik** [comment]
Updated documentation here: [Iowa StreamEst](https://doimspp.sharepoint.com/:o:/r/sites/GS-UMidWIM/_layouts/15/Doc.aspx?sourcedoc=%7B86ee3545-8271-46a1-b16f-158b12f19ba3%7D&action=edit&wd=target(Introduction.one%7CFA6D5C1D-D7FB-4D35-B339-992EF3438208%2FIowa%20StreamEst%7CA0291771-75FB-4D73-8850-B033B07C8AA9%2F)onenote%3Ahttps%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FGS-UMidWIM%2FShared%20Documents%2FProjects%2FStreamstats%20Ecosystem%2FKJ%27s%20Guide%20to%20StreamStats%201%2FIntroduction.one#Iowa%20StreamEst%26section-id%3D%7BFA6D5C1D-D7FB-4D35-B339-992EF3438208%7D%26page-id%3D%7BA0291771-75FB-4D73-8850-B033B07C8AA9%7D%26end).

File: src/appConfig.js [hunk 1]
```diff
@@ -76,7 +79,9 @@ configuration.queryparams =
         'GageStatsServicesStatGroups': '/statisticgroups/',
         'GageStatsServicesNearest': '/stations/Nearest?lat={0}&lon={1}&radius={2}&geojson=false&includeStats=true',
         'GageStatsServicesNetwork': '/stations/Network?lat={0}&lon={1}&distance={2}&includeStats=true&geojson=false',
-        'GageStatsServicesBounds': '/stations/Bounds?xmin={0}&xmax={1}&ymin={2}&ymax={3}&geojson=true'
+        'GageStatsServicesBounds': '/stations/Bounds?xmin={0}&xmax={1}&ymin={2}&ymax={3}&geojson=true',
+        'FlowAnywhereEstimates': '/models/FLA/estimate?state=IA',
```
Comment (harper-wavra) [inline src/appConfig.js]: This could be '/models/FLA/estimate?state={0}' in case it ever gets added to other states.

File: src/Controllers/FlowAnywhereController.ts [hunk 2]
```diff
@@ -0,0 +1,257 @@
...
+//             
+// 
+//   purpose:  Flow Anywhere Controller
+//          
+//discussion:
+
+
+//Comments
+//07.24.2019 jkn - Created
+
```
Comment (harper-wavra) [inline src/Controllers/FlowAnywhereController.ts]: You could probably get rid of this text, or just edit it.

**Review by harper-wavra — COMMENTED** [review]
It is working really well for me and I think the loader looks and works nicely!

I am wondering if we should merge this into dev, or should we have Pete and/or the IA cooperators look at it first? If we do merge into dev we should rebuild first.

**Review by harper-wavra — APPROVED** [review]
