### PR TITLE
Fixes #1537 - Feedback on Annual Flow Plot with Flood-Frequency Statistics

### LINKED ISSUE #1537: Feedback on Annual Flow Plot with Flood-Frequency Statistics
Feedback from Pete (@USGSPMM3) on Annual Flow Plot with Flood-Frequency Statistics (original issue #1424) 

- [x] This might be my monitor, but the plot does not completely fit in my scrollable area. I have to scroll up and down continuously to see all of the information. See image below.
- [x] A user should be able to hover over the flood quantile lines and see the values.  (original issue #1514)
     - Going to try using a data series instead of plotlines for the flood quantile lines
     - Will need to see what the earliest start date and latest end date is for the other data series 
     - New way to turn on and off all AEP lines at the same time (they appear individually in legend)
- [x] When  zoom to a specific time period, the y-scale resets and doesn't allow me to see how far below the flood quantile values I am. 
     - This will probably be resolved if we change the AEP plotlines to a data series (the previous item in this list)  
- [x] I like the NWS plot default which shows the day of year of peaks with the flow duration shading and a dark blue line with current streamflow. The timing of peaks plotted on a single year is informative for flood-frequency analyses. See figure below.   
     - Ask Pete about this 
- [x] If we do the above (plot ALL peaks on day of year regardless of which year is selected, I think there should be a toggle to plot peaks a) on actual date of occurrence, or b) plot all peaks on day of year. The quick zoom button allows the user to quickly zoom to the current data.
- [x] When I click on the date to change it, the entry box is further up and left then I would like. When entering dates, a tab should move the user to the next entry area. If the box was bigger it would be easier to see the calendar for selecting dates if a user didn't want to enter them manually. 
     - We've [consulted Mitch](https://wim-usgs.slack.com/archives/C2PG1BC3S/p1676997538284229)
- [x] If there is missing data, don't draw a line across the missing period. Stop the line and restart.
     - May need to rebuild the time series to add Null values for dates that were excluded in the time series (https://nwis.waterdata.usgs.gov/usa/nwis/peak/?format=rdb&site_no=02173500&startDT=2021-04-29&endDT=2022-12-30)
     -  Maybe there is a built-in way to deal with this in Highcharts?
- [x] In the zoom options for 1m, 3m, etc, I was expecting to have those zoom to the LAST 1m or 3m of data. What it appears to do is set the x-axis zoom to that scale regardless of where you are in the full time period. 
     - Ask Pete about these buttons-- do we want them? These are just the default ones.
- [x] Add option to add the NWS forecast data (maybe leave on for default plot?)
     - Ask Pete about this 
- [x] "Reset Zoom" button is not working as expected
     - May have gotten messed up due to Highcharts Stock 

image
image

### PR DESCRIPTION
**Pull request by maggiejaenicke**
Closes #1537. 
These lines are showing as errors in the Typescript file but are working as intended: 843, 1128.

### CODE REVIEW

File: src/Controllers/GagePageController.ts [hunk 1]
```diff
@@ -884,6 +1104,772 @@ module StreamStats.Controllers {
...
+                }
+            }
+            var finalIndex = this.formattedDailyFlow.length-1;
+            var finalYear = (finalPeakorDailyDate).getUTCFullYear(); //currently using the final daily flow point as latest year, but sometimes gage has more recent peaks
+            //return an array with a date each day between first recording and last
+            function dateRange(startDate, endDate, steps = 1) {
+                const dateArray = [];
+                let currentDate = new Date(startDate);
+                while (currentDate <= new Date(endDate)) {
+                    dateArray.push(new Date(currentDate));
```
Comment (amedenblik) [inline src/Controllers/GagePageController.ts:1129]: `currentDate` is already a Date object, so I think you can remove the `new Date()`. This also gets rid of the error on this line.

```suggestion
                    dateArray.push(currentDate);
```-

File: src/Views/gagepage.html [hunk 2]
```diff
@@ -225,13 +225,27 @@ <h4 class="modal-title">StreamStats Gage Page</h4>
...
-                        <highchart id="chart1" config="vm.chartConfig"></highchart>
-                    </div>
+                        <div class="well well-sm" style="background-color:#EBF0F5;" ng-if="vm.chartConfig">
+                            <div class="plot-filters">
+                                <input type="checkbox" ng-if="vm.formattedFloodFreq.length > 0 || vm.formattedAltFloodFreq.length > 0" id="toggleFloodStats" name="toggleFloodStats" ng-model="vm.showFloodStats" ng-change="vm.toggleFloodStats()" checked>
+                                <label for="toggleFloodStats" ng-if="vm.formattedFloodFreq.length > 0 || vm.formattedAltFloodFreq.length > 0" > Show Flood Statistics:</label>
+                                <select id="gageFloodStatsSelect" ng-if="vm.formattedFloodFreq.length > 0 || vm.formattedAltFloodFreq.length > 0 " style="width:10%" name="gageFloodStatsSelect" ng-model="vm.selectedFloodFreqStats" ng-options="floodFreqStat.name for floodFreqStat in vm.allFloodFreqStats" ng-change="vm.chooseFloodStats()" ng-disabled="vm.showFloodStats == false"></select>&nbsp;&nbsp;&nbsp;
```
Comment (amedenblik) [inline src/Views/gagepage.html]: Is it possible to reformat this area so that the select box can be wide enough to show the full name of the Statistic Group? Maybe that checkbox and select box just needs its own line.
image


```suggestion
                                <label for="toggleFloodStats" ng-if="vm.formattedFloodFreq.length > 0 || vm.formattedAltFloodFreq.length > 0" > Show Flood Statistics:</label>
                                <select id="gageFloodStatsSelect" ng-if="vm.formattedFloodFreq.length > 0 || vm.formattedAltFloodFreq.length > 0 " style="width:10%" name="gageFloodStatsSelect" ng-model="vm.selectedFloodFreqStats" ng-options="floodFreqStat.name for floodFreqStat in vm.allFloodFreqStats" ng-change="vm.chooseFloodStats()" ng-disabled="vm.showFloodStats == false"></select>&nbsp;&nbsp;&nbsp;                      
```

File: src/Controllers/ExtensionModalController.ts [hunk 3]
```diff
@@ -94,6 +94,7 @@ module StreamStats.Controllers {
                 });
                 if (newval != oldval) this.getNWISDailyValues();
             });
+            console.log(this.dateRange.dates)
```
Comment (amedenblik) [inline src/Controllers/ExtensionModalController.ts]:
```suggestion
```

File: src/images/shadedLegend.PNG
Comment (amedenblik) [inline src/images/shadedLegend.PNG:1]: I don't think this is being used, so we should either use it or delete it.

File: src/Views/sidebarview.html [hunk 4]
```diff
@@ -171,7 +171,7 @@ <h5>Supported search strings:</h5>
                             <div class="col-md-3 "><button class="link-btn" ng-click="vm.showScenarioHelp = !vm.showScenarioHelp"><i class="fa fa-question-circle"></i></button></div>
                         </div>
 
-                        <div ng-init="vm.showScenarioHelp = false" ng-show="vm.showScenarioHelp">
+                        <div ng-="vm.showScenarioHelp = false" ng-show="vm.showScenarioHelp">
```
Comment (amedenblik) [inline src/Views/sidebarview.html]: Maybe this was an accident?

```suggestion
                        <div ng-init="vm.showScenarioHelp = false" ng-show="vm.showScenarioHelp">

```

File: src/Views/gagepage.html [hunk 5]
```diff
@@ -225,13 +225,27 @@ <h4 class="modal-title">StreamStats Gage Page</h4>
...
+                                <label for="logScale" ng-if="vm.formattedDailyFlow.length > 0"> Log Scale</label>&nbsp;&nbsp;
+                                <button ng-click="vm.resetZoom()" style="height:80%">Reset Zoom</button><br>
+                                <!-- <button ng-click="vm.updateShadedStats()" style="height:80%">Update Shaded Stats</button><br> -->
+                                <!-- <label for="dischargeStart"> Date Range:</label>
+                                <input date-range-picker class="form-control date-picker" type="text" style="width:20%; height:80%" id="dischargeStart" length=10 ng-model="vm.dailyDatesOnly" min="vm.startAndEnd[0]" max="vmstartAndEnd[1]" options="vm.dailyDatesOnly"> -->
+                                <label for="dischargeStart"> Start Date:</label>
+                                <input type="text" style="width:11%; height:80%" id="dischargeStart" length=10 placeholder="MM-DD-YYYY">
+                                <label for="dischargeEnd"> End Date:</label>
+                                <input type="text" style="width:11%; height:80%" id="dischargeEnd" length=10 placeholder="MM-DD-YYYY">
```
Comment (amedenblik) [inline src/Views/gagepage.html]: Thoughts on using the [date input selector](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date) instead of text?

We should also populate these input fields with the default start/end date when the page loads.

```suggestion
                                <input type="date" style="width:11%; height:80%" id="dischargeStart">
                                <label for="dischargeEnd"> End Date:</label>
                                <input type="date" style="width:11%; height:80%" id="dischargeEnd">
```

**Review by amedenblik — CHANGES_REQUESTED** [review]
Great job tackling this large amount of feedback!

- [x] I'm not sure the "If there is missing data, don't draw a line across the missing period. Stop the line and restart." part of the issue is working. See gage 12340000: looks like there is a line for Daily Streamflow where there is no data
image

File: src/Views/gagepage.html (hunk 2 above)
Comment (maggiejaenicke) [reply src/Views/gagepage.html]: I made it longer so that "Annual Exceedance Probability" fits in full, but for gages that have alternate stats it's just long enough to show "Alternative Annual Exceedance". All the other stats (1-Day Low Flow, etc.) are much shorter. I didn't want it to be too long to the point where it takes up a ton of space, but let me know what you think, though, and it can definitely be even longer.

File: src/Views/gagepage.html (hunk 5 above)
Comment (maggiejaenicke) [reply src/Views/gagepage.html]: Defaults are populated! I'm definitely open to using the date input selector instead, but I was confused looking at examples so went for this one instead.

File: src/appConfig.js [hunk 6]
```diff
@@ -12,9 +12,7 @@ configuration.baseurls =
         'StormRunoffServices': 'https://test.streamstats.usgs.gov/runoffmodelingservices',
         'ScienceBase': 'https://gis.usgs.gov/sciencebase2',
         'GageStatsServices': 'https://test.streamstats.usgs.gov/gagestatsservices',
-        'WeightingServices': 'https://ss-weightingservices.streamstats.usgs.gov',
-        'SCStormRunoffServices': 'https://streamstats.usgs.gov/local/scrunoffservices',
-        'NationalMapServices': 'https://hydro.nationalmap.gov/arcgis/rest/services',
```
Comment (harper-wavra) [inline src/appConfig.js]: I think we want to keep these

**Review by harper-wavra — COMMENTED** [review]
These updates are great!

- It seems like the log scale isnt working. I went to gage 06348500, and when I click Log Scale the only thing that happens is the y axis disappears. 
- Maybe we could add a loader when we click on 'Plot Peaks on Latest Year' just to show the user its working but might take a while?

File: src/Views/gagepage.html [hunk 7]
```diff
@@ -225,13 +225,24 @@ <h4 class="modal-title">StreamStats Gage Page</h4>
...
+                                <label for="toggleFloodStats" ng-if="vm.formattedFloodFreq.length > 0 || vm.formattedAltFloodFreq.length > 0" > Show Flood Statistics:</label>
+                                <select id="gageFloodStatsSelect" ng-if="vm.formattedFloodFreq.length > 0 || vm.formattedAltFloodFreq.length > 0 " style="width:19.25%" name="gageFloodStatsSelect" ng-model="vm.selectedFloodFreqStats" ng-options="floodFreqStat.name for floodFreqStat in vm.allFloodFreqStats" ng-change="vm.chooseFloodStats()" ng-disabled="vm.showFloodStats == false"></select>&nbsp;&nbsp;&nbsp;                      
+                                <input type="checkbox" ng-if="vm.formattedPeakDates.length > 0" id="togglePeaks" name="togglePeaks" ng-model="vm.peaksOnYear" ng-change="vm.togglePeakYear()" checked>
+                                <label for="togglePeaks" ng-if="vm.formattedPeakDates.length > 0"> Plot Peaks on Latest Year&nbsp;&nbsp;</label>
```
Comment (amedenblik) [inline src/Views/gagepage.html]: Recommended text edit to make it more clear what this means

```suggestion
                                <label for="togglePeaks" ng-if="vm.formattedPeakDates.length > 0"> Plot Annual Streamflow Peaks on Latest Year&nbsp;&nbsp;</label>
```

File: src/Views/gagepage.html [hunk 8]
```diff
@@ -225,13 +225,24 @@ <h4 class="modal-title">StreamStats Gage Page</h4>
...
-                        <highchart id="chart1" config="vm.chartConfig"></highchart>
-                    </div>
+                        <div class="well well-sm" style="background-color:#EBF0F5;" ng-if="vm.chartConfig">
+                            <div class="plot-filters">
+                                <input type="checkbox" ng-if="vm.formattedFloodFreq.length > 0 || vm.formattedAltFloodFreq.length > 0" id="toggleFloodStats" name="toggleFloodStats" ng-model="vm.showFloodStats" ng-change="vm.toggleFloodStats()" checked>
+                                <label for="toggleFloodStats" ng-if="vm.formattedFloodFreq.length > 0 || vm.formattedAltFloodFreq.length > 0" > Show Flood Statistics:</label>
+                                <select id="gageFloodStatsSelect" ng-if="vm.formattedFloodFreq.length > 0 || vm.formattedAltFloodFreq.length > 0 " style="width:19.25%" name="gageFloodStatsSelect" ng-model="vm.selectedFloodFreqStats" ng-options="floodFreqStat.name for floodFreqStat in vm.allFloodFreqStats" ng-change="vm.chooseFloodStats()" ng-disabled="vm.showFloodStats == false"></select>&nbsp;&nbsp;&nbsp;
```
Comment (amedenblik) [inline src/Views/gagepage.html]:
```suggestion
                                <select id="gageFloodStatsSelect" ng-if="vm.formattedFloodFreq.length > 0 || vm.formattedAltFloodFreq.length > 0 " style="width:31%" name="gageFloodStatsSelect" ng-model="vm.selectedFloodFreqStats" ng-options="floodFreqStat.name for floodFreqStat in vm.allFloodFreqStats" ng-change="vm.chooseFloodStats()" ng-disabled="vm.showFloodStats == false"></select><br><br>                
```

File: src/Views/gagepage.html [hunk 9]
```diff
@@ -225,13 +225,24 @@ <h4 class="modal-title">StreamStats Gage Page</h4>
...
-                        <input type="checkbox" ng-if="vm.formattedFloodFreq.length > 0" id="yesAEPLines" name="yesAEPLines" ng-model="vm.plotlines" ng-change="vm.togglePlotLines()" checked>
-                        <label for="yesAEPLines" ng-if="vm.formattedFloodFreq.length > 0"> AEP Plot Lines&nbsp;&nbsp;</label>
-                        <input type="checkbox" ng-if="vm.formattedDailyFlow.length > 0" id="logScale" name="logScale" ng-model="vm.logScale" ng-change="vm.toggleLogLinear()" checked>
-                        <label for="logScale" ng-if="vm.formattedDailyFlow.length > 0"> Log Scale</label>
-                        <highchart id="chart1" config="vm.chartConfig"></highchart>
-                    </div>
+                        <div class="well well-sm" style="background-color:#EBF0F5;" ng-if="vm.chartConfig">
+                            <div class="plot-filters">
+                                <input type="checkbox" ng-if="vm.formattedFloodFreq.length > 0 || vm.formattedAltFloodFreq.length > 0" id="toggleFloodStats" name="toggleFloodStats" ng-model="vm.showFloodStats" ng-change="vm.toggleFloodStats()" checked>
```
Comment (amedenblik) [inline src/Views/gagepage.html]: Let's move this whole input section to be below the plot

**Review by amedenblik — CHANGES_REQUESTED** [review]

**Review by harper-wavra — COMMENTED** [review]
I took a look at all our comments and the issues again, I think the only thing missing is to remove the line if there is no data. This was working for me at one point so not sure what happened. [example](https://user-images.githubusercontent.com/59063181/234608620-804810e7-aa71-42f9-bc67-93abc8f4e9a2.png). Once this is fixed, I would be good to merge into gageplots and push to the dev site so others can take a look.


Gages kept freezing up for me when I was doing this review, so much so I had to use task manager to close my browser. Though I think this is part of a larger issue & separate issue, just noticed it more in this review. If we keep adding plots my fear is things will keep getting slower. We could just load data for one plot at a time and let the user pick which plot they want to see, or add a note saying that it might a couple minutes to load? Maybe you guys ( @amedenblik @maggiejaenicke ) have other ideas how to handle this, or we could bring it up at our next check in? (or maybe you guys are not seeing this and it is a my laptop problem)

**Review by harper-wavra — APPROVED** [review]

**Comment by harper-wavra** [comment]
I will rebuild, merge and push to the dev site this afternoon.
